admin/manual_install: debian-repository
grommunio/grommunio-documentation pull request #1
Opened 2022-08-14 01:15 UTC by crpb

you don't always have to do it the old way :eyes:
and i guess that "[trusted=yes]" is a relic from [here](https://community.grommunio.com/d/182-solved-debian-11-repository/4)?

2022-08-14 06:52 UTC, crpb reviewed
nevermind on apt-transport-https.. it's a dummy

2022-08-16 07:41 UTC, StefanAkie requested changes

2022-08-16 07:41 UTC, StefanAkie commented on admin/manual_install.rst
> +^^^^^^^^^^^^
```suggestion
^^^^^^
```

2022-08-16 09:48 UTC, jengelh commented
Merged via squash ec8edef, updated with d62e375

2022-08-16 09:48 UTC, closed without merging